version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=super_password
      - POSTGRES_USER=faas_api
      - POSTGRES_DB=faas_api

  backend:
    build: ./containers/django/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./faas/backend/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    cap_add:
      - SYS_PTRACE

  reactjs:
    build: ./containers/reactjs/
    volumes:
      - ./faas/frontend/app/:/project/app
    ports:
      - "8080:8080"
    command: npm start
    depends_on:
      - backend
