# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0002_auto_20161028_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
