# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0003_auto_20161028_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='owner',
        ),
    ]
