# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0005_crashreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashreport',
            name='payload',
            field=models.CharField(max_length=100000),
        ),
    ]
