# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0006_auto_20161121_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crashreport',
            old_name='owner',
            new_name='task',
        ),
    ]
