# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0008_task_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rax', models.CharField(max_length=20)),
                ('rbx', models.CharField(max_length=20)),
                ('rcx', models.CharField(max_length=20)),
                ('rdx', models.CharField(max_length=20)),
                ('rsi', models.CharField(max_length=20)),
                ('rdi', models.CharField(max_length=20)),
                ('r8', models.CharField(max_length=20)),
                ('r9', models.CharField(max_length=20)),
                ('r10', models.CharField(max_length=20)),
                ('r11', models.CharField(max_length=20)),
                ('r12', models.CharField(max_length=20)),
                ('r13', models.CharField(max_length=20)),
                ('r14', models.CharField(max_length=20)),
                ('r15', models.CharField(max_length=20)),
                ('rbp', models.CharField(max_length=20)),
                ('rsp', models.CharField(max_length=20)),
                ('rip', models.CharField(max_length=20)),
                ('crash_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuzzer_task.CrashReport')),
            ],
        ),
    ]
