# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0010_auto_20161216_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registers',
            name='crash_report',
        ),
        migrations.AddField(
            model_name='crashreport',
            name='registers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fuzzer_task.Registers'),
            preserve_default=False,
        ),
    ]
