# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0011_auto_20161216_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('r', 'Running'), ('e', 'Ended'), ('k', 'Killed')], default='r', max_length=1),
        ),
    ]
