# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0012_auto_20161216_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
