# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzer_task', '0013_auto_20161216_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crashreport',
            name='registers',
        ),
        migrations.AddField(
            model_name='registers',
            name='crash_report',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fuzzer_task.CrashReport'),
            preserve_default=False,
        ),
    ]
